# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Blog
#tagline:          'Blog'
description:      'Some news from <a href="https://twitter.com/antoinelyset">@antoinelyset</a>.'
url:              http://blog.antoinelyset.com

author:
  name:           'Antoine Lyset'
  url:            https://twitter.com/antoinelyset

paginate:         4

# Custom vars

github: antoinelyset
twitter: antoinelyset
